### ISSUE TITLE
Windows 10 1709 build 16299.192

### ISSUE THREAD

**Issue by Sn00z3r** [breenmachine/RottenPotatoNG#1]
Hi,

Just wanted to let you know that this does not work on windows 10 1709 build 16299.192 (error code 1314, meaning **A required privilege is not held by the client**.

I did not have time yet to troubleshoot the issue, I will when I have time, however I just wanted to let you know :)!

Keep up the awesome work!

**Comment by Sn00z3r** [comment]
After some testing I think I might have made a mistake by saying you need an elevated prompt. Because you need to run this executable as a user who has the right to impersonate, which I guess NT SERVICE can.

Let me know if this is correct, if so, you can close this issue ;)

**Comment by Sn00z3r** [comment]
I have tested this using a MSSQL user (NT SERVICE) and it works like a charm, you can close this remark!

**Comment by breenmachine** [comment]
If you're running from the command prompt, you just need to make sure that you have the right privilege with "whoami /priv".

**Comment by Sn00z3r** [comment]
Yep, my apologies, didn't have much sleep and it shows :p

**Comment by breenmachine** [comment]
No problem!
