### ISSUE TITLE
RottenPotatoNG vs LonelyPotato

### ISSUE THREAD

**Issue by LyesH4ck** [breenmachine/RottenPotatoNG#2]
Hey !

For your information I used RottenPotatoNG in a CTF...
I recompiled it to exec a specific exe (metasploit Windows meterpreter: Reverse_HTTPS).
When the payload is executed, I get a meterpreter session .. But it hanged .. No response from the meterpreter.

Compiled in x64 with SDK Windows 10.0.16299.0 (not the v8...)

I've used the Lonely Version : https://github.com/decoder-it/lonelypotato, the exe file downloaded on the git, and it worked very well. Tested on the same exe file (windows meterpreter).

 I dunno.. Maybe there is a problem ? Or maybe the problem is my SDK version.

Anyway very good job !

**Comment by breenmachine** [comment]
Nice! That's awesome. Not sure why your shells were dieing, but I'm glad you got another version of it working. I've been in contact with the author of lonelypotato and he's been doing some research to clean up some loose ends with this technique.

**Comment by decoder-it** [comment]
Hello, which type of API call did you use in my (lonelypotato)  version?

**Comment by LyesH4ck** [comment]
Hello,
I’m not sure to understand.
But I downloaded the .exe file from the Lonely Git, and uploaded the binary via my Meterpreter shell.
I got a Shell CMD and tested the 2 options: u and t.
They both worked.

Is that what you asked ?

**Comment by decoder-it** [comment]
OK, well 'u' uses the SeImpersonate and 't' the SeAggignPrimaryToken privilege. In which ctf did test it?

**Comment by LyesH4ck** [comment]
Hack The Box, Name server is Bart

**Comment by decoder-it** [comment]
Yes id did this box too ;-) if you want to know more about this  modified exe read here: https://decoder.cloud/2018/01/13/potato-and-tokens/
